### ISSUE TITLE
Add ability to upload file from a URL

### ISSUE THREAD

**Issue by dchassin** [openfido/openfido-client#118]
Right now, only local files can be uploaded. We would like the ability to upload data from a URL.

**Comment by Thistleman** [comment]
This issue has been addressed with a new utility script, added into the new [utilities](https://github.com/openfido/utilities) repository. 

Inclusion of the script will automatically find URLs in the provided files and submitted forms, and if they are publicly accessible, download their content. Tested using content from public github repositories.
